spring:
  application:
    name: demo
  web:
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  profiles:
    active: dev

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: DEBUG
